bpwhelan/GameSentenceMiner

main.py

Nicely Compressed webp as well
Fixes #2

Get Image from Video

---

main.py

Will now create a temp directory for all temp files to go into, will delete itself after the script stopped.
Closes #5

Improve tempfile creation/cleanup

---

.gitignore
README.md
config.py
main.py
vosk_helper.py

Downloads the japanese language model from Vosk, and does local transcribing to figure out where the voice ends.
closes #7

7 cut out azure

---

.gitignore
config_EXAMPLE.toml
config_reader.py
main.py
vosk_helper.py

Closes #9 
Will Encode if it needs to, or it will extract

Add Audio Extension Config and better logging

---

.gitignore
update.py

Update Script, sorta forces changes, but backs up all changed files.

Add Update Script

---

anki.py
config_EXAMPLE.toml
config_reader.py
ffmpeg.py
main.py
vosk_helper.py

Also Ignore Audio if there is no voice whatsoever

Added Offset Config

---

anki.py
main.py

Changed to global, Else it would add audio we don't want it to on secondary vocab

Discard Audio for subsequent Cards

---

main.py
util.py

Changed to gamename.date_string.extension

Update File name

---

anki.py
config_EXAMPLE.toml
config_reader.py
ffmpeg.py
main.py

28 catch card deleted

---

anki.py
config_EXAMPLE.toml
config_reader.py
ffmpeg.py
main.py
obs.py
vosk_helper.py

Get Game from Scene in OBS optionally.
Improve BGM filtering

Scene switch game switch

---

config_EXAMPLE.toml
config_reader.py
main.py
offset_updater.py
requirements.txt
vosk_helper.py

Implemented the ability to adjust offset values via the terminal and automatically restart the script once the values are successfully saved.

Offset change on terminal

---

clipboard.py
config_EXAMPLE.toml
config_reader.py
ffmpeg.py
main.py
obs.py

added config for sentence field and polling rate
Handle new clipboard events that happen after the card is mined, in case we don't know about the card fast enough

handle clipboard updates better

---

anki.py
config_reader.py
main.py
vosk_helper.py

This is to backfill cards that match the clipboard, in case you are replaying a game and already have cards, and only need screenshot/sentenceaudio

Add Backfill_mode

---

ffmpeg.py
main.py
silero_trim.py
update.py
util.py
vosk_helper.py
whisper_helper.py

shell=True if on linux, i've always found it to be necessary on linux, but wished i could go without it. Also disable hotkeys on linux.

improved linux compat

---

.gitignore
README.md
anki.py
config_gui.py
configuration.py
ffmpeg.py
gametext.py
main.py
obs.py
silero_trim.py
steam_launcher.py
update.py
util.py
vosk_helper.py
whisper_helper.py
yuzu_launcher.py

Also releasing yuzu_launcher here, and some other cleanup

Remove tempfile replacing

---

.github/workflows/main.yml
.gitignore
config_gui.py
configuration.py
gametext.py
hooks/hook-plyer.py
hooks/hook-silero_vad.py
hooks/hook-vosk.py
main.py
obs.py
requirements.txt
util.py
yuzu_launcher.py

Tray icon
actions to auto build exe
better config opening/reloading
reconnect obs
open logs through tray

Lots of stuff

---

GameSentenceMiner/anki.py
GameSentenceMiner/config_gui.py
GameSentenceMiner/ffmpeg.py
GameSentenceMiner/gametext.py
GameSentenceMiner/gsm.py
pyproject.toml

New setting, field for previous line's image

Add previous image

---

GameSentenceMiner/anki.py
GameSentenceMiner/config_gui.py
GameSentenceMiner/ffmpeg.py
GameSentenceMiner/gametext.py
GameSentenceMiner/gsm.py
GameSentenceMiner/utility_gui.py
pyproject.toml

Text Event Consumption Re-write
closes #69

2.3.8 - Release

---

GameSentenceMiner/anki.py
GameSentenceMiner/config_gui.py
GameSentenceMiner/configuration.py
GameSentenceMiner/ffmpeg.py
GameSentenceMiner/gsm.py
GameSentenceMiner/model.py
GameSentenceMiner/notification.py
GameSentenceMiner/obs.py
GameSentenceMiner/utility_gui.py
electron-src/main/main.ts
package.json
pyproject.toml

don't throw error if line is received before utility gui is initialized on startup, verify obs folder and gsm path to watch is same fix Notifications throwing error if do not disturb is on fix crash if line is outside of replay buffer
sync certain configs across all profiles
fix previous screenshot/line for multi-line
add open gsm folder button in electron tray

more tweaks

---

.gitmodules
GameSentenceMiner/anki.py
GameSentenceMiner/configuration.py
GameSentenceMiner/gametext.py
GameSentenceMiner/gsm.py
GameSentenceMiner/obs.py
GameSentenceMiner/ocr/ocrconfig.py
GameSentenceMiner/ocr/owocr_area_selector.py
GameSentenceMiner/ocr/owocr_helper.py
electron-src/assets/index.html
electron-src/assets/ocr.html
electron-src/main/main.ts
electron-src/main/store.ts
electron-src/main/ui/ocr.ts
package.json
pyproject.toml

Adding OWOCR Management Capabilities to GSM, very minimal changes to the GSM code, just enough to handle a different message that has a timestamp included.

Owocr integration

---

README.md

Some minor suggested changes that I think would improve the readme

Fix typos and wording in README.md

---

GameSentenceMiner/obs.py
GameSentenceMiner/ocr/gsm_ocr_config.py
GameSentenceMiner/ocr/owocr_area_selector.py
GameSentenceMiner/ocr/owocr_helper.py
electron-src/assets/index.html
electron-src/main/store.ts
electron-src/main/ui/ocr.ts
electron-src/main/util.ts
package.json
pyproject.toml

Adds Ability to use OBS as image source for OCR, this should open up OCR for linux folk.

OBS OCR / LINUX OCR

---

GameSentenceMiner/util/configuration.py
GameSentenceMiner/web/database_api.py
GameSentenceMiner/web/events.py
GameSentenceMiner/web/static/css/search.css
GameSentenceMiner/web/static/css/shared.css
GameSentenceMiner/web/static/css/stats.css
GameSentenceMiner/web/static/js/database.js
GameSentenceMiner/web/static/js/search.js
GameSentenceMiner/web/static/js/shared.js
GameSentenceMiner/web/static/js/stats.js
GameSentenceMiner/web/stats.py
GameSentenceMiner/web/templates/components/navigation.html
GameSentenceMiner/web/templates/components/theme-styles.html
GameSentenceMiner/web/templates/database.html
GameSentenceMiner/web/templates/search.html
GameSentenceMiner/web/templates/stats.html
GameSentenceMiner/web/templates/text_replacements.html
GameSentenceMiner/web/templates/utility.html
GameSentenceMiner/web/texthooking_page.py
GameSentenceMiner/web/websockets.py
electron-src/assets/index.html

Hi!
Firstly this PR is obviously vibe coded, but maybe not in an extreme way:
1. I write a very long message on what I want with technical details
2. I get the AI to write a plan
3. I correct that plan
4. I get it to follow that plan, and then I just go through the results
I have been testing this a lot and looking at it a lot, and i think its stable enough to potentially be released to the public 
currently its only accessible at the /stats endpoint, not in GSM itself 
The database management functionality works, i have tested all of it
search works, i have tested it
stats all work, it shows... stats
do npm start and on the texthooker page go to /stats - there are links to everything else on there :) lmk what you think!

Add stats to GSM

---

GameSentenceMiner/web/templates/stats.html

So users can take screenshots of the typical things they may want to post

Move heatmap below today's overview

---

GameSentenceMiner/web/database_api.py

Small quality of life change, now when you get all the games from the DB they are sorted.
useful for manage games:

Sort DB games list by chars

---

GameSentenceMiner/config_gui.py
GameSentenceMiner/util/configuration.py
GameSentenceMiner/vad.py

Not tested
Shows you what the API looks like, %s is what chrome uses for browsers
i noticed theres support for ai tts but its commented out, maybe will uncomment that at some point
not tested yet

added local tts
